source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
#inhibit_all_warnings!

def common
	pod 'WeexSDK'
	pod 'WeexPluginLoader'
    pod 'ZLPhotoBrowser'
    pod 'AFNetworking', '~> 3.0'
end

target 'ImagePicker' do
    common
end


